[package]
name = "slimevr_overlay"
version = "0.0.0"
authors = ["Ryan Butler <thebutlah@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ovr_overlay = { path = "../ovr_overlay" }
eyre = "0.6"
ctrlc = "3"
log = "0.4"
pretty_env_logger = "0.4"
color-eyre = "0.6"
nalgebra = "0.30"
lazy_static = "1"
