[package]
name = "slimevr_overlay"
version = "0.0.0"
authors = ["Ryan Butler <thebutlah@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openxr = { version = "0.16", features = ["static"] }
eyre = "0.6"
