[target.riscv32imac-unknown-none-elf]
# runner = "espflash --monitor"

[build]
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",

  # For defmt
  "-C",
  "link-arg=-Tdefmt.x",
]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core", "alloc"]

[env]
# You can override this via environment variable when building or by changing it here
DEFMT_LOG = "debug"
